#!/usr/bin/node
$(document).ready(function() {
  const apiUrl = 'https://swapi-api.hbtn.io/api/films/?format=json';
  $.ajax({ url: apiUrl, dataType: 'json',
    success: function(data) {
      const movies = data.results;
      const listElement = $('#list_movies');
      $.each(movies, function(index, movie) {
        listElement.append('<li>' + movie.title + '</li>');
      });
    },
    error: function(xhr, status, error) {
      console.error('Error fetching data:', error);
    }
  });
});
